----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:28:43,027

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:30:27,992

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/awstest/settings.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:30:28,308

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:30:37,913

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1818
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:30:44,528

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-13 04:30:44,529

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:30:44,530

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 456
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:36:35,837

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:36:42,488

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1818
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:36:47,925

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-13 04:36:47,926

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:36:47,927

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 456
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:37:01,804

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:50:47,420

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:50:52,767

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1818
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:50:52,997

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:50:53,037

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 200 155758
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:50:53,057

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 200 58072
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:50:53,356

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 200 190253
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 07:50:53,471

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Not Found: /favicon.ico
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 07:50:53,472

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /favicon.ico HTTP/1.1" 404 2200
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:50:53,581

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 200 625953
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:50:59,287

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-13 07:50:59,289

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:50:59,290

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 456
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:52:53,482

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1862
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:52:56,116

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-13 07:52:56,116

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:52:56,117

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 456
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:54:11,823

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:54:12,114

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:58:21,918

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 07:58:22,213

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 08:00:19,467

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 08:00:19,759

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 08:00:34,437

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 08:00:34,733

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:15:18,217

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:42,823

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1862
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:43,074

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 200 155758
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:43,082

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:43,099

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 200 58072
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-14 04:16:43,421

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Not Found: /favicon.ico
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-14 04:16:43,421

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /favicon.ico HTTP/1.1" 404 2199
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:48,517

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 200 190253
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:48,665

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 200 625953
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:50,144

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2 HTTP/1.1" 301 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:50,148

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container HTTP/1.1" 301 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:50,187

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:50,189

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:16:50,190

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:36:38,644

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1862
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:40,206

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2006
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:43,262

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2006
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:43,397

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:43,397

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:43,410

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:43,552

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:43,554

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:45,248

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:45,249

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:45:45,250

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:18,063

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:23,297

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:23,335

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:23,335

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:23,350

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:23,445

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:23,490

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:25,204

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:25,204

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:55:25,206

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:57:13,295

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:57:13,616

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:57:19,594

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:57:19,595

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:57:19,596

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 04:58:55,907

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:00:06,924

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:00:07,245

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:07:26,079

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:07:26,398

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:08:00,787

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:08:01,120

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:08:41,712

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:08:42,033

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:08:57,775

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:08:58,085

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:09:02,905

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:09:02,958

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:09:02,959

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:09:02,971

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:09:03,120

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:09:03,121

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-14 05:09:09,643

Source log file: /root/awstest/awstest/container/views.py line: 17

Traceback (most recent call last):
  File "/root/awstest/awstest/container/views.py", line 14, in get
    response = collections.OrderdDict(container.query())
AttributeError: module 'collections' has no attribute 'OrderdDict'

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:09:09,648

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:09:09,650

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-14 05:09:09,657

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Internal Server Error: /container/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-14 05:09:09,658

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 500 13183
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:10:12,995

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:10:13,323

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:10:15,626

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:10:15,945

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:10:47,139

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:10:53,877

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:10:53,879

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:10:53,880

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:13:59,114

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:13:59,430

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:14:02,723

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:14:07,826

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 66
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:14:07,829

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:14:07,830

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:23:24,744

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/awstest/settings.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:23:25,065

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:28,649

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:28,963

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:37,306

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:40,494

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:40,495

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:40,506

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:40,644

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:40,645

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:42,717

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 66
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:42,718

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:25:42,719

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:31:36,352

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:31:36,689

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:31:42,631

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:31:47,770

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 66
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:31:47,771

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:31:47,772

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:38:22,583

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:38:22,906

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:39:49,088

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:39:49,408

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:06,400

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:06,735

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:15,420

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:15,466

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:15,466

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:15,483

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:15,661

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:15,661

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:17,973

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 66
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:42:17,974

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-14 05:42:17,975

Source log file: /root/awstest/awstest/ec2/views.py line: 22

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/views.py", line 19, in get
    logging.info(type())
TypeError: type() takes 1 or 3 arguments

----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-14 05:42:17,987

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Internal Server Error: /ec2/
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-14 05:42:17,988

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 500 13297
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:53:27,099

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 05:53:27,408

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:16:15,929

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:16:19,232

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:16:19,235

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:16:19,254

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:16:19,393

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:16:19,393

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:27:32,394

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:27:32,704

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:28:27,784

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:28:28,092

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:30:13,963

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:30:14,290

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:51,846

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:52,155

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:53,839

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2080
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:53,887

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:53,900

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:53,925

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:54,086

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:54,086

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:57,698

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:57,700

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:31:57,701

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:33:39,144

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/container.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:33:39,464

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:35:09,802

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:35:10,119

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:40:09,561

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2125
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:40:14,211

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:40:14,212

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:40:14,213

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:40:54,232

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2125
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:40:56,048

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:40:56,049

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:40:56,050

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:41:52,399

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2163
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:41:54,422

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:41:54,422

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:41:54,424

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:42:41,554

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2088
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:42:43,071

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2088
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:42:44,907

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:42:44,908

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:42:44,909

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:44:03,762

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2092
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:44:05,364

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:44:05,365

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 06:44:05,366

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:00:00,023

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2021
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:00:03,231

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:00:03,233

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:00:03,247

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:00:03,382

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/css/bootstrap.min.css.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:00:03,382

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/bootstrap.min.js.map HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:00:05,123

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:00:05,124

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:00:05,126

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:01:23,335

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2043
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:01:25,389

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:01:25,389

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:01:25,391

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:03:14,116

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2022
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:03:15,532

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:03:15,532

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:03:15,534

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:09:43,521

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 2022
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:09:54,787

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:09:54,789

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:09:54,804

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:12:29,835

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1978
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:12:33,236

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:12:33,237

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:12:33,238

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:13:00,181

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1987
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:13:01,820

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:13:01,821

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:13:01,822

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:14:06,864

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1987
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:14:08,367

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:14:08,368

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:14:08,370

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:16:21,805

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1914
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:16:32,996

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:16:32,997

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:16:32,998

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:16:54,957

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1849
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:16:55,003

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:16:57,070

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:16:57,070

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:16:57,072

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:18:25,891

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:18:25,891

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:18:25,893

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:18:27,056

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:18:27,057

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:18:27,058

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:18:28,077

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:18:28,078

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:18:28,079

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:29:53,197

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1914
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:29:55,161

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:29:55,162

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:29:55,163

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:30:22,033

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1916
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:31:26,787

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1979
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:32:26,138

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1849
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:28,009

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1990
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:28,089

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /static/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:29,970

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:29,971

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:29,972

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:31,771

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:31,771

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:31,773

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:54,979

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:54,980

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:54,981

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:57,971

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1990
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:59,539

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:59,540

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:37:59,542

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:38:17,937

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1989
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:38:19,527

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:38:19,528

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:38:19,529

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:38:21,817

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:38:21,818

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:38:21,819

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 457
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-14 07:45:21,303

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1989
